/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sorting_array */

#ifndef _Included_Sorting_array
#define _Included_Sorting_array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sorting_array
 * Method:    ArraySorting
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Sorting_1array_ArraySorting
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
