/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimpleClass */

#ifndef _Included_SimpleClass
#define _Included_SimpleClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SimpleClass
 * Method:    changecountvalue
 * Signature: (LSimpleClass;)V
 */
JNIEXPORT void JNICALL Java_SimpleClass_changecountvalue
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
