/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exception_Difftypes */

#ifndef _Included_Exception_Difftypes
#define _Included_Exception_Difftypes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exception_Difftypes
 * Method:    intMethod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Exception_1Difftypes_intMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Exception_Difftypes
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_Exception_1Difftypes_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Exception_Difftypes
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Exception_1Difftypes_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Exception_Difftypes
 * Method:    doit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Exception_1Difftypes_doit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
